let suggestions = [
    "Holden Hall",
    "Math and Statistics",
    "Maddox Engineering Research Center",
    "West Hall",
    "Sneed Residence Hall",
    "Gordon Residence Hall",
    "Bledsoe Residence Hall",
    "Civil Engineering",
    "Engineering & Technology Lab",
    "Bob L. Herd Department of Petroleum Engineering",
    "Creative Movement Studio",
    "Sports Performance Center",
    "Football Training Complex",
    "Jones AT&T Stadium (Football)",
    "Frazier Alumni Pavilion",
    "Marsha Sharp Center for Student Athletics",
    "Mechanical Engineering North",
    "Mechanical Engineering South",
    "Chemical Engineering",
    "Industrial, Manufacturing, and Systems Engineering",
    "Engineering Center",
    "Computer Center",
    "Knapp Residence Hall",
    "Horn Residence Hall",
    "McKenzie-Merket Alumni Center",
    "Hance Chapel, Kent R.",
    "Talkington Residence Hall, J.T. & Margaret",
    "Music",
    "Student Union Building",
    "Library, University",
    "Agricultural Pavilion",
    "Southwest Collection/Special Collections Library",
    "Psychology",
    "Charles E. Maedgen Jr. Theatre",
    "Burkhart Center for Autism Education and Research",
    "Classical & Modern Languages and Literatures",
    "Goddard Range & Wildlife Management",
    "Plant Sciences",
    "Bayer Plant Science",
    "English & Philosophy",
    "Education",
    "Memorial Circle",
    "Rec Center, Robert H. Ewalt Student",
    "Rec Sports Leisure Pool",
    "United Supermarkets Arena",
    "Urbanovsky University Park",
  ];

suggestions = suggestions.sort();
